Dev to Master
oicr-gsi/variantEffectPredictor pull request #1
Opened 2020-03-23 20:48 UTC by rishi-shah12

2020-03-30 16:45 UTC, mlaszloffy requested changes

2020-03-30 16:45 UTC, mlaszloffy commented on variantEffectPredictor.wdl
> +  if (defined(targetBed) == true) {
Can the task calls be collapsed into:
1) if defined(targetBed) call targetBedTask
2) call vep {      input: 
vcfFile = select_first([targetBedTask.vcfFile,vcfFile],
vcfIndex = select_first([targetBedTask.vcfIndex, vcfIndex]),
...
3) if toMAF call vcf2maf

And then outputs modified to:
 File outputVcf = vep.vepVcfOutput
 File? outputMaf = vcf2maf.mafOutput

2020-04-30 20:40 UTC, prisnir-zz requested changes

2020-04-30 20:40 UTC, prisnir commented on variantEffectPredictor.wdl
> +      input: vcfFile = vep.vepVcfOutput,
The input for this should be input VCF and not the VEP annotated VCF

2020-04-30 20:40 UTC, prisnir commented on variantEffectPredictor.wdl
> +      input: vcfFile = vep.vepVcfOutput,
Looks like:
vcf2maf is enabled for tumor only VCFs
and it reads VEP annotated VCF to run vcf2maf

2020-04-30 20:40 UTC, prisnir commented on tests.json
> +         "variantEffectPredictor.vepCacheDir": "$VEP_HG19_CACHE_ROOT/.vep",
Can we also include a test case for GRCh38 ?

2020-05-07 18:30 UTC, xuemeiluo commented
retest this please

2020-05-08 13:56 UTC, mlaszloffy approved these changes

2020-05-08 13:59 UTC, prisnir-zz approved these changes

2020-05-08 17:38 UTC, merged